{
 "title": "Google Online Boutique System Analytics",
 "tags": [
  "spe",
  "online-boutique"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Microservice Container CPU Load (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[1m])) by (container) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Microservice Memory Footprint (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"}) by (container) / 1024 / 1024",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Prometheus Scraped HTTP Request Rates (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total[1m])) by (handler)",
     "legendFormat": "Handler: {{handler}}"
    }
   ]
  },
  {
   "title": "Prometheus Scraped HTTP Error Rates (4xx/5xx req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total{code=~\"4.*|5.*\"}[1m])) by (handler)",
     "legendFormat": "Handler: {{handler}} (Error)"
    }
   ]
  }
 ]
}